// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeuwPmGKpi6GrV-yan0wTglR7k_QgNI0w',
    appId: '1:40647075508:web:f2c2078e38d83b2071d9e1',
    messagingSenderId: '40647075508',
    projectId: 'atm-finder-4406e',
    authDomain: 'atm-finder-4406e.firebaseapp.com',
    storageBucket: 'atm-finder-4406e.firebasestorage.app',
    measurementId: 'G-01Q6QMXDD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUI_5md4_S7RChXD41XjIJFW-8O0QAXc4',
    appId: '1:40647075508:android:1148758e163c09bc71d9e1',
    messagingSenderId: '40647075508',
    projectId: 'atm-finder-4406e',
    storageBucket: 'atm-finder-4406e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC06F9u25qSaO-Xhm8BR50glKMicCee7dg',
    appId: '1:40647075508:ios:72bcec545773b1a171d9e1',
    messagingSenderId: '40647075508',
    projectId: 'atm-finder-4406e',
    storageBucket: 'atm-finder-4406e.firebasestorage.app',
    iosBundleId: 'iq.krd.kurdistanatm',
  );
}
